-dontwarn dalvik.system.VMRuntime
-keep class org.lsposed.hiddenapibypass.Helper$* {*;}
-keepclassmembers class org.lsposed.hiddenapibypass.Helper$* {*;}
-keep class org.lsposed.hiddenapibypass.HiddenApiBypass {*;}